In [1]:
import tensorflow as tf
from transformers import TFAutoModel, AutoTokenizer
from datasets import load_dataset


In [2]:
model_path = 'bert-base-uncased'

In [3]:
model = TFAutoModel.from_pretrained(model_path)


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [4]:
tokenizer = AutoTokenizer.from_pretrained(model_path)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [5]:
inputs = tokenizer("Hello World", padding = True, truncation = True, return_tensors = 'tf')
print(inputs)

{'input_ids': <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 101, 7592, 2088,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 1, 1, 1]], dtype=int32)>}


In [6]:
output = model(inputs)
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 4, 768), dtype=float32, numpy=
array([[[-0.16888325,  0.13606334, -0.13940078, ..., -0.62511253,
          0.05217267,  0.3671455 ],
        [-0.3632744 ,  0.14121872,  0.879987  , ...,  0.10432988,
          0.28875676,  0.37267905],
        [-0.69859445, -0.6987977 ,  0.06450161, ..., -0.22103643,
          0.00986908, -0.5939799 ],
        [ 0.83098286,  0.12366741, -0.15119024, ...,  0.10309598,
         -0.67792666, -0.26285192]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-9.06153381e-01, -3.11153024e-01, -6.21653378e-01,
         7.74093091e-01,  2.89865613e-01, -1.90243453e-01,
         9.24707890e-01,  1.81800961e-01, -5.05039275e-01,
        -9.99944508e-01, -2.37347841e-01,  8.76212180e-01,
         9.77160513e-01,  2.58089840e-01,  9.38015044e-01,
        -6.90611601e-01, -5.21052063e-01, -5.49152911e-01,
         3.57588738e-01, -7.59822488e

## Import HuggingFace Dataset

In [7]:
emotions = load_dataset('SetFit/emotion')

Repo card metadata block was not found. Setting CardData to empty.


Generating train split:   0%|          | 0/16000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [8]:
emotions

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label', 'label_text'],
        num_rows: 2000
    })
})

## Tokenization of Inputs

In [9]:
def tokenize(batch):
    return tokenizer(batch["text"], padding = True, truncation = True)
    

In [10]:
emotions_encoded = emotions.map(tokenize, batched = True, batch_size = None)

Map:   0%|          | 0/16000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [11]:
emotions_encoded

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2000
    })
})

In [12]:
emotions_encoded['train'][0]

{'text': 'i didnt feel humiliated',
 'label': 0,
 'label_text': 'sadness',
 'input_ids': [101,
  1045,
  2134,
  2102,
  2514,
  26608,
  102,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'token_type_ids': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 '

In [13]:
type(emotions_encoded)

datasets.dataset_dict.DatasetDict

In [14]:
emotions_encoded.set_format('tf', 
                           columns = ['input_ids', 'attention_mask', 'token_type_ids', 'label'])

In [15]:
emotions_encoded['train'][0]

{'label': <tf.Tensor: shape=(), dtype=int64, numpy=0>,
 'input_ids': <tf.Tensor: shape=(87,), dtype=int64, numpy=
 array([  101,  1045,  2134,  2102,  2514, 26608,   102,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0])>,
 'token_type_ids': <tf.Tensor: shape=(87,), dtype=int64, numpy=
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [16]:
type(emotions_encoded)

datasets.dataset_dict.DatasetDict

In [17]:
batch_size = 64

In [18]:
def order(inp):
    data = list(inp.values())
    return ({
        'input_ids': data[1],
        'attention_mask': data[2],
        'token_type_ids': data[3]
    }, data[0])
    

In [19]:
train_dataset = tf.data.Dataset.from_tensor_slices(emotions_encoded['validation'][:])
train_dataset = train_dataset.batch(batch_size).shuffle(1000)
train_dataset = train_dataset.map(order, num_parallel_calls = tf.data.AUTOTUNE)

In [20]:
validation_dataset = tf.data.Dataset.from_tensor_slices(emotions_encoded['validation'][:])
validation_dataset = validation_dataset.batch(batch_size).shuffle(1000)
validation_dataset = validation_dataset.map(order, num_parallel_calls = tf.data.AUTOTUNE)

In [21]:
test_dataset = tf.data.Dataset.from_tensor_slices(emotions_encoded['test'][:])
test_dataset = test_dataset.batch(batch_size).shuffle(1000)
test_dataset = test_dataset.map(order, num_parallel_calls = tf.data.AUTOTUNE)

In [22]:
class BERTForClassification(tf.keras.Model):
    def __init__(self, bert_model, num_classes):
        super().__init__()
        self.bert = bert_model
        self.fc = tf.keras.layers.Dense(num_classes, activation = 'softmax')
    
    # Forward Pass
    def call(self, inputs):
        x = self.bert(inputs)[1]
        return self.fc(x)
        

In [23]:
classifier = BERTForClassification(model, num_classes = 6)
classifier.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate = 1e-5),
    loss = tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics = ['accuracy'])

In [24]:
history = classifier.fit(
train_dataset,
validation_data = validation_dataset,
epochs = 3)

Epoch 1/3


I0000 00:00:1726678510.483059      69 service.cc:145] XLA service 0x790610f89db0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1726678510.483117      69 service.cc:153]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
I0000 00:00:1726678510.483121      69 service.cc:153]   StreamExecutor device (1): Tesla T4, Compute Capability 7.5
I0000 00:00:1726678510.685776      69 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


32/32 [==============================] - 127s 1s/step - loss: 1.6228 - accuracy: 0.3400 - val_loss: 1.5651 - val_accuracy: 0.3525
Epoch 2/3
32/32 [==============================] - 36s 1s/step - loss: 1.5496 - accuracy: 0.4080 - val_loss: 1.4820 - val_accuracy: 0.4595
Epoch 3/3
32/32 [==============================] - 35s 1s/step - loss: 1.3950 - accuracy: 0.5055 - val_loss: 1.2696 - val_accuracy: 0.5595


In [25]:
classifier.evaluate(test_dataset)

32/32 [==============================] - 19s 266ms/step - loss: 1.2959 - accuracy: 0.5355


[1.2958934307098389, 0.5354999899864197]