In [33]:
import numpy as np


[ 1.  1.  1. -1. -1.  1. -1. -1.  1.  1.]
[-1. -1.  1.  1. -1.  1.  1. -1. -1. -1.]
[-1. -1. -1.  1.  1. -1.  1.  1. -1. -1.]
[-1. -1. -1.  1.  1. -1.  1.  1. -1. -1.]
[-1. -1. -1.  1.  1. -1.  1.  1. -1. -1.]
[-1. -1. -1.  1.  1. -1.  1.  1. -1. -1.]
[ 1.  1.  1. -1. -1.  1. -1. -1.  1.  1.]
[-1. -1. -1.  1.  1. -1.  1.  1. -1. -1.]
[-1. -1. -1.  1.  1. -1.  1.  1. -1. -1.]
[ 1.  1.  1. -1. -1.  1. -1. -1.  1.  1.]
[-1. -1. -1.  1.  1. -1.  1.  1. -1. -1.]
[-1. -1. -1.  1.  1. -1.  1.  1. -1. -1.]
[ 1.  1.  1. -1. -1.  1. -1. -1.  1.  1.]
[ 1. -1.  1. -1. -1.  1. -1.  1.  1. -1.]
[-1. -1. -1.  1.  1. -1.  1.  1. -1. -1.]
[-1. -1. -1.  1.  1. -1.  1.  1. -1. -1.]
[ 1.  1.  1. -1.  1.  1. -1. -1.  1.  1.]
[-1. -1.  1.  1. -1.  1.  1.  1. -1.  1.]
[-1. -1. -1.  1.  1. -1.  1.  1. -1. -1.]
[ 1.  1.  1. -1. -1.  1. -1. -1.  1.  1.]


In [ ]:
# Training phase
def hopfield_network_train(patterns):
    # Set input shape
    num_neurons = patterns.shape[1]

    # Set weight matrix shape
    # Initialize weight matrix with zeros
    weights = np.zeros((num_neurons, num_neurons))
    for pattern in patterns:
        pattern = pattern.reshape((num_neurons, 1))

        # Compute dot product to find the weights
        weights += np.dot(pattern, pattern.T)
    
    # Set the diagonal elements to zero to avoid self connections
    np.fill_diagonal(weights, 0)
    return weights



In [ ]:
# Testing Phase
def hopfield_network_recall(patterns, weights, num_iterations=5):
    # Set the recall pattern shape
    num_neurons = patterns.shape[1]
    recalled_patterns = []

    # For each pattern
    for pattern in patterns:
        pattern = pattern.reshape((num_neurons, 1))
        # For a fixed number of iterations
        for _ in range(num_iterations):
            # Update neuron states 
            recalled_pattern = np.sign(np.dot(weights, pattern))
            pattern = recalled_pattern
        recalled_patterns.append(recalled_pattern)
    return np.array(recalled_patterns)

# Define your patterns as numpy arrays
train_patterns = np.array([
    [1, 1, -1, -1, 1, 1, -1, -1, 1, 1],
    [-1, 1, 1, -1, -1, 1, -1, -1, 1, 1],
    [-1, -1, 1, 1, -1, 1, 1, -1, 1, 1],
    [1, -1, -1, 1, -1, -1, 1, 1, -1, -1],
    [1, 1, -1, -1, 1, -1, -1, 1, -1, -1],
    [-1, -1, 1, 1, -1, -1, 1, 1, -1, -1],
    [1, -1, 1, -1, -1, 1, -1, 1, 1, -1],
    [-1, 1, -1, 1, 1, -1, 1, -1, -1, 1],
    [-1, -1, -1, 1, 1, -1, 1, 1, -1, -1],
    [1, 1, 1, -1, -1, 1, 1, -1, 1, 1]
])

# Train the Hopfield network
weights = hopfield_network_train(train_patterns)

# Test the network by recalling the patterns
test_patterns = np.array([
    [-1, -1, -1, -1, 1, 1, -1, -1, 1, 1],
    [-1, 1, 1, 1, -1, -1, 1, 1, 1, 1],
    [-1, -1, -1, 1, 1, -1, 1, -1, -1, -1],
    [-1, -1, -1, 1, 1, 1, -1, 1, -1, -1],
    [-1, 1, -1, -1, 1, -1, -1, -1, -1, -1],
    [-1, -1, 1, 1, -1, -1, 1, -1, -1, -1],
    [-1, -1, 1, -1, -1, 1, -1, 1, 1, -1],
    [-1, -1, -1, 1, 1, -1, 1, -1, -1, 1],
    [-1, -1, -1, 1, -1, -1, 1, 1, -1, -1],
    [1, -1, 1, -1, -1, 1, 1, -1, 1, 1],
    [1, -1, -1, 1, 1, 1, -1, -1, -1, 1],
    [-1, -1, 1, 1, 1, -1, 1, -1, 1, -1],
    [-1, -1, -1, -1, 1, 1, -1, 1, 1, 1],
    [1, -1, 1, -1, -1, 1, -1, 1, 1, -1],
    [1, 1, 1, -1, 1, -1, -1, 1, -1, -1],
    [-1, 1, -1, 1, 1, 1, -1, 1, -1, -1],
    [1, -1, -1, -1, -1, 1, 1, 1, -1, 1],
    [-1, 1, 1, 1, -1, -1, 1, -1, 1, -1],
    [1, -1, 1, 1, -1, -1, 1, 1, -1, -1],
    [1, 1, -1, -1, -1, -1, 1, 1, 1, 1]
])
recalled_patterns = hopfield_network_recall(test_patterns, weights)


In [ ]:
# Print the recalled patterns
for pattern in recalled_patterns:
    print(pattern.flatten())

In [34]:
def calculate_hamming_distance(pattern1, pattern2):
    # Compute the element-wise XOR of the two patterns
    xor_result = np.logical_xor(pattern1, pattern2)
    # Count the number of True values (bit mismatches)
    hamming_distance = np.sum(xor_result)
    return hamming_distance

In [35]:
# Evaluate pattern recall accuracy
num_patterns = len(test_patterns)
total_hamming_distance = 0

for i in range(num_patterns):
    original_pattern = test_patterns[i]
    recalled_pattern = recalled_patterns[i]
    hamming_distance = calculate_hamming_distance(original_pattern, recalled_pattern)
    total_hamming_distance += hamming_distance

# Calculate pattern recall accuracy as the percentage of correct bits
num_total_bits = num_patterns * len(test_patterns[0])
accuracy = (num_total_bits - total_hamming_distance) / num_total_bits * 100

print("Pattern Recall Accuracy: {:.2f}%".format(accuracy))


Pattern Recall Accuracy: 100.00%
